<a href="https://colab.research.google.com/github/GANYMEDEBANK/Features/blob/main/RFE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, mean_absolute_error

In [20]:
#collecting data
data = load_breast_cancer()
#loading data in panda data frame
df = pd.DataFrame(data.data, columns = data.feature_names)
#adding the target column
df['Result'] = data.target

In [21]:
X = df.drop(columns = 'Result', axis = 1)
y = df['Result']

In [22]:
#train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33, random_state = 0)

In [23]:
#model
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [24]:
X_train_pred = model.predict(X_train)
dt_accu = accuracy_score(y_train,X_train_pred)
print(dt_accu)

0.9448818897637795


In [25]:
#accuracy on train data
X_test_pred = model.predict(X_test)
dt_accu = accuracy_score(y_test, X_test_pred)
mae = mean_absolute_error(y_test,X_test_pred)

In [26]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(X_test_pred, y_test)
cm

array([[ 66,   6],
       [  1, 115]])

In [27]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

In [28]:
from sklearn.feature_selection import RFE

lr = LogisticRegression()

rfe = RFE(estimator = lr, n_features_to_select = 13, step = 1)
rfe.fit(X_train_std, y_train)
X_train_sub = rfe.transform(X_train_std)

In [29]:
rfe.support_

array([False, False, False, False, False, False,  True,  True, False,
       False,  True, False,  True,  True, False,  True, False, False,
       False, False,  True,  True,  True,  True, False, False,  True,
        True,  True, False])

In [30]:
df.columns[1:][rfe.support_]

Index(['mean concave points', 'mean symmetry', 'texture error', 'area error',
       'smoothness error', 'concavity error', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

In [31]:
selected_X_train = pd.DataFrame(rfe.transform(X_train))
selected_X_test = pd.DataFrame(rfe.transform(X_test))

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RFE was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RFE was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [32]:
selected_X_test.head()

0        1       2      3      4         5      6      7       8   \
0  0.14450  0.08172  0.3906  3.093  33.67  0.022650  16.41  29.66  113.30   
1  0.02772  0.02068  0.2084  1.314  17.58  0.008082  14.35  34.23   91.29   
2  0.02087  0.02652  0.2142  1.606  19.25  0.009238  14.91  19.31   96.53   
3  0.02475  0.01374  0.2300  1.661  20.56  0.013770  16.22  25.26  105.80   
4  0.02562  0.02923  0.1839  1.170  14.16  0.004899  13.30  22.81   84.46   

      9        10       11      12  
0  844.4  0.51060  0.20510  0.3585  
1  632.9  0.13900  0.06005  0.2444  
2  688.9  0.06260  0.08216  0.2136  
3  819.7  0.15650  0.07530  0.2636  
4  545.9  0.04833  0.05013  0.1987

In [33]:
#model
model = LogisticRegression()
model.fit(selected_X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [34]:
X_train_pred = model.predict(selected_X_train)
dt_accu = accuracy_score(y_train,X_train_pred)
print(dt_accu)

0.9422572178477691


In [35]:
#accuracy on train data
X_test_pred = model.predict(selected_X_test)
dt_accu = accuracy_score(y_test, X_test_pred)
mae = mean_absolute_error(y_test,X_test_pred)

In [36]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(X_test_pred, y_test)
cm

array([[ 66,   4],
       [  1, 117]])